<?php
/**
 *   Project: MEWA Hospital Intranet
 *   Developed by: Muhyadin Abdullahi (muhidin.rashid@mewa.or.ke) & Salim Juma (salim.silaha@mewa.or.ke).
 *
 *    Copyright (c) 2018: This project is open-sourced software licensed under the GNU Affero General Public License v3.0 (https://opensource.org/licenses/AGPL-3.0).
 *
 */

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class SynchronizeSyhosDeduction extends SynchronizeSyhosResource
{
    use DispatchesJobs, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        parent::handle(); // TODO: Change the autogenerated stub
    }

    public function getSyhosService()
    {
        // TODO: Implement getSyhosService() method.
    }
}
